---
- name: genexpipeline
  hosts: all
  remote_user: jenkins
  gather_facts: no
  become: true
  tasks:
     - name: verify on hosts
       command: ls -la /root 
       register: ls_out
     - debug: var=ls_out.stdout
     - name : Install Telnet using apt
       apt : name=telnet update_cache=yes
